os: linux
dist: bionic
language: shell
git:
  quiet: true
env:
  global:
    - HADOLINT_VERSION=1.18.1
services:
- docker
before_install:
- sudo curl -L https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint
- sudo chmod 755 /usr/local/bin/hadolint
- CLIENT_PORT=$(cat /dev/urandom|od -N2 -An -i|awk -v f=10000 -v r=19999 '{printf "%i\n", f + r * $1 / 65536}')
- "[ $(netstat -an | grep LISTEN | grep :$CLIENT_PORT | wc -l) -eq 0 ] || { ./$0 && exit 0 || exit 1; }"
install:
- docker build
  --no-cache
  --tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .
script:
- DOCKERCONTAINER=$(docker run -d -p 127.0.0.1:${CLIENT_PORT}:3128 ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT})
- sleep 5
- docker ps -f id=${DOCKERCONTAINER}
- curl -s 127.0.0.1:${CLIENT_PORT} | grep -q squid
- hadolint Dockerfile
- docker stop ${DOCKERCONTAINER} && docker rm -fv ${DOCKERCONTAINER}
after_success:
- docker tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} quay.io/aminvakil/squid
- docker login quay.io -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD"
- docker push quay.io/aminvakil/squid
